apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-frontend
  labels:
    app: bms-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms-frontend
  template:
    metadata:
      labels:
        app: bms-frontend
    spec:
      containers:
        - name: bms-frontend
          image: sagar18v/bms:latest
          ports:
            - containerPort: 80
